theme: minima
title: My Blog
author: Lexi Roshkovan
email: lexirosh7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My final project for AP Comp Sci P.

# social links
twitter_username: lexirosh # DO NOT include the @ character, or else the build will fail!
github_username:  lexirosh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
